export const CHANGE_POKEMON = "CHANGE_POKEMON"
export const GET_POKEMONS_SUCCESS = "GET_POKEMONS_SUCCESS"
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST"
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST"